get_planning_scene_server:
  ros__parameters:
    use_sim_time: true
    
    # Topic and frame settings
    point_cloud_topic: "/camera_head/depth/color/points"
    rgb_image_topic: "/camera_head/color/image_raw"
    target_frame: "base_link"
    
    # Cropping settings
    enable_cropping: true
    crop_min_x: 0.10
    crop_max_x: 1.1
    crop_min_y: 0.00
    crop_max_y: 0.90
    crop_min_z: -inf
    crop_max_z: inf
    
    # Plane and object segmentation parameters
    max_iterations: 100
    distance_threshold: 0.02
    z_tolerance: 0.05
    angle_tolerance: 0.996194698 # cos(5.0 * M_PI / 180.0)
    plane_segmentation_threshold: 0.02
    min_cluster_size: 100
    max_cluster_size: 25000
    cluster_tolerance: 0.02
    normal_estimation_k: 30
    w_inliers: 1.0
    w_size: 1.0
    w_distance: 1.0
    w_orientation: 1.0
    
    # Legacy parameters (to be removed later)
    max_plane_segmentation_iterations: 1000
    plane_segmentation_distance_threshold: 0.01
    shape_fitting_max_iterations: 1000
    shape_fitting_distance_threshold: 0.01
    shape_fitting_min_radius: 0.01
    shape_fitting_max_radius: 0.1
    shape_fitting_normal_distance_weight: 0.1
    shape_fitting_normal_search_radius: 0.05
    
    # Debug output settings
    output_directory: "/home/ubuntu/Downloads/"
    debug_pcd_filename: "debug_cloud.pcd"
