# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  gripper_base_to_gripper_left2:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_base_to_gripper_right2:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_base_to_gripper_right3:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_controller:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left3_to_gripper_left1:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right3_to_gripper_right1:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0
  link1_to_link2:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0
  link2_to_link3:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0
  link3_to_link4:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0
  link4_to_link5:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0
  link5_to_link6:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0
  link6_to_link6flange:
    has_velocity_limits: true
    max_velocity: 2.7925270000000002
    has_acceleration_limits: false
    max_acceleration: 0