# This file configures the controller management for MoveIt, specifying which controllers are available,
# the joints each controller handles, and the type of interface (e.g. FollowJointTrajectory).
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager  # Specifies the controller manager to use.

# Define the controllers configured using the ROS 2 Control framework.
moveit_simple_controller_manager:
  controller_names:
    - arm_controller   # Name of the controller for the robotic arm.
    #- grip_controller  # Name of the controller for the gripper.
    - grip_action_controller # Other controller for the gripper (recommended)

  # Configuration for the arm_controller.
  arm_controller:
    action_ns: follow_joint_trajectory   # ROS action namespace to which MoveIt sends trajectory commands.
    type: FollowJointTrajectory          # Type of the controller interface; follows a joint trajectory.
    default: true                        # This controller is the default for the joints listed below.
    joints:                              # List of joints that the arm_controller manages.
      - link1_to_link2
      - link2_to_link3
      - link3_to_link4
      - link4_to_link5
      - link5_to_link6
      - link6_to_link6flange

  # Configuration for the grip_controller.
  #grip_controller:
    #action_ns: follow_joint_trajectory  
    #type: FollowJointTrajectory         
    #default: false                    
    #joints:                           
      #- gripper_controller      
  
  # Configuration for the grip_action_controller.    
  grip_action_controller:  
    action_ns: gripper_cmd 
    type: GripperCommand
    default: true
    joints:
      - gripper_controller       

           

